parameters:
#    striide_calendar.example.class: Striide\CalendarBundle\Example

services:
#    striide_calendar.example:
#        class: %striide_calendar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
